version: '3.8'

networks:
  app-network:
    driver: bridge
volumes:
  sql_db_volume:
    driver: local
  
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-1_proxy
    container_name: micro-videos-nginx
    restart: always
    tty: true
    ports:
        - "8000:80"
    volumes:
        - ./2_backend:/var/www
    networks:
        - app-network
    depends_on:
        - app
  app:
      build:
        context: .
        dockerfile: Dockerfile-2_backend
      container_name: micro-videos-app
      entrypoint: ./1_backend_env/entrypoint.sh
      environment:
        - _DB_HOST=db
        - _DB_DATABASE=code_micro_videos
        - _DB_USERNAME=root
        - _DB_PASSWORD=root
        - _TEST_DB_DATABASE=code_micro_videos_test
      volumes: 
        - ./2_backend:/var/www
      networks:
        - app-network
      depends_on:
        - db
        - redis
  db:
    image: mysql
    container_name: micro-videos-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - sql_db_volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
        - 6379
    networks:
        - app-network
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - app-network